/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.component';
const styles_AppComponent: any[] = ['h1[_ngcontent-%COMP%] { font-weight: bold; }'];
export const RenderType_AppComponent: i0.RendererType2 = i0.ɵcrt({
  encapsulation: 0, styles: styles_AppComponent,
  data: {}
});
export function View_AppComponent_0(_l: any): i0.ɵViewDefinition {
  return i0.ɵvid(0, [
    (_l()(), i0.ɵeld(0, 0, (null as any), (null as any), 1, 'h1', ([] as any[]), (null as any), (null as any), (null as any), (null as any), (null as any))),
    (_l()(), i0.ɵted(1, (null as any), ['Hello world from ', '!']))
  ],
  (null as any), (_ck, _v) => {
    var _co: i1.AppComponent = _v.component;
    const currVal_0: any = _co.title;
    _ck(_v, 1, 0, currVal_0);
  });
}
export function View_AppComponent_Host_0(_l: any): i0.ɵViewDefinition {
  return i0.ɵvid(0, [
    (_l()(), i0.ɵeld(0, 0, (null as any), (null as any), 1, 'app-root', ([] as any[]), (null as any), (null as any), (null as any), View_AppComponent_0, RenderType_AppComponent)),
    i0.ɵdid(1, 49152, (null as any), 0, i1.AppComponent, ([] as any[]), (null as any), (null as any))
  ], (null as any), (null as any));
}
export const AppComponentNgFactory: i0.ComponentFactory<i1.AppComponent> = i0.ɵccf('app-root',
  i1.AppComponent, View_AppComponent_Host_0, {}, {}, ([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvZmJ1bGljL1Byb2plY3RzL2FuZ3VsYXItY29tcGlsZXItcGxheWdyb3VuZC9zcmMvYXBwL2FwcC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9mYnVsaWMvUHJvamVjdHMvYW5ndWxhci1jb21waWxlci1wbGF5Z3JvdW5kL3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cyIsIm5nOi8vL2hvbWUvZmJ1bGljL1Byb2plY3RzL2FuZ3VsYXItY29tcGlsZXItcGxheWdyb3VuZC9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9ob21lL2ZidWxpYy9Qcm9qZWN0cy9hbmd1bGFyLWNvbXBpbGVyLXBsYXlncm91bmQvc3JjL2FwcC9hcHAuY29tcG9uZW50LnRzLkFwcENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMT5IZWxsbyB3b3JsZCBmcm9tIHt7IHRpdGxlIH19ITwvaDE+IiwiPGFwcC1yb290PjwvYXBwLXJvb3Q+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBSTthQUFBOztJQUFBO0lBQUE7Ozs7b0JDQUo7TUFBQTthQUFBO1VBQUE7OzsifQ==
